eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service-pkuvmyhxkq-oa.a.run.app/eureka/
    instance:
      hostname: localhost
