
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://https://discovery-app-27kusmptja-oa.a.run.app/eureka/
    instance:
      hostname: localhost
